// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5GIwcqNvgkvk0kAktUgKjq9Eeblsq3Ng',
    appId: '1:491778800633:web:9ac48f26bab8f4849d5b28',
    messagingSenderId: '491778800633',
    projectId: 'flutter-demo-vnptit5',
    authDomain: 'flutter-demo-vnptit5.firebaseapp.com',
    storageBucket: 'flutter-demo-vnptit5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLCDpV3i0DgAaWFBKmlTFv7RC7fCc1JFo',
    appId: '1:491778800633:android:77fbd75b64591e749d5b28',
    messagingSenderId: '491778800633',
    projectId: 'flutter-demo-vnptit5',
    storageBucket: 'flutter-demo-vnptit5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK7Jqq9S6SNJsA5xXMYAM6av2sUw0kO9c',
    appId: '1:491778800633:ios:78ef9c9aa8e1085b9d5b28',
    messagingSenderId: '491778800633',
    projectId: 'flutter-demo-vnptit5',
    storageBucket: 'flutter-demo-vnptit5.appspot.com',
    iosClientId:
        '491778800633-rfa0c4ns3v1cq57dpae9p172ia1tdcal.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo_App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK7Jqq9S6SNJsA5xXMYAM6av2sUw0kO9c',
    appId: '1:491778800633:ios:78ef9c9aa8e1085b9d5b28',
    messagingSenderId: '491778800633',
    projectId: 'flutter-demo-vnptit5',
    storageBucket: 'flutter-demo-vnptit5.appspot.com',
    iosClientId:
        '491778800633-rfa0c4ns3v1cq57dpae9p172ia1tdcal.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo_App',
  );
}
